# Generated by Django 2.2.10 on 2020-03-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='API_KEY',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='API_SECRET',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
