# Generated by Django 2.1.5 on 2020-03-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_todoitem_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
