# Generated by Django 2.1.5 on 2020-03-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20200325_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
