# Generated by Django 2.1.5 on 2020-03-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200325_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High priority'), (2, 'Medium priority'), (3, 'Low priority')], default=2, verbose_name='Priority'),
        ),
    ]
